# Generated by Django 4.1.7 on 2023-03-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.TextField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
