# Generated by Django 4.1.7 on 2023-03-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_removed_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_id',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
