# Generated by Django 4.1.7 on 2023-03-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_product_id_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.TextField(max_length=500),
        ),
    ]
