# Generated by Django 4.1.7 on 2023-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2e', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
